[metadata]
name = p0_py
version = 0.0.0
description = TODO: Package description
maintainer = arrgusr
maintainer_email = erik.pena@ingenieria.unam.edu
license = MIT

[options]
packages = find:
install_requires =
    setuptools
zip_safe = True

[options.packages.find]
exclude =
    test

[options.data_files]
share/ament_index/resource_index/packages =
    resource/p0_py
share/p0_py =
    package.xml

[options.entry_points]
console_scripts =
    primer_node_py = p0_py.primer_nodo:main
    subscriber_node_py = p0_py.subscriber_node:main
    nodo_pub_sndl = p0_py.nodo_pub_sndl:main
    nodo_sub_pub_rads = p0_py.nodo_sub_pub_rads:main
    q_plan_node = p0_py.q_plan:main
    scara_control_node = p0_py.scara_control:main
    diagonal_planner1 = p0_py.scara_diagonal_line_node:main
    diagonal_planner2 = p0_py.scara_diagonal2_line:main
[develop]
script_dir = $base/lib/p0_py

[install]
install_scripts = $base/lib/p0_py
